"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AUTO_ADVANCE_S, DECISION_LEAD_S, choose, seek } from "@/lib/api";
import type { Beat, SessionView } from "@/lib/types";
import DecisionOverlay from "./DecisionOverlay";
import Hud from "./Hud";
import StoryTree from "./StoryTree";
import VideoStage, { type StageHandle } from "./VideoStage";

/**
 * The playback brain.
 *
 * One deliberate deviation from DESIGN.md 6.2, which specifies: clip ends ->
 * freeze on the last frame -> options fly in -> 4s countdown. Implemented that
 * way, every beat spends 4 of every 18 seconds as a still image *in silence*,
 * because on this backend the score is baked into each clip rather than played
 * as a separate bed -- so the same section's "音乐床不中断" cannot hold. Raising
 * the overlay 4s *before* the clip ends instead keeps picture and sound running
 * underneath the decision, and the swap still lands exactly on the clip boundary,
 * so nothing is truncated and there is no gap.
 *
 * Decisiveness is still rewarded, just differently: an early click is recorded
 * and committed the instant the clip ends, rather than saving the player a wait
 * they no longer have. And the freeze-frame path is still built and still used --
 * it is what covers the case the Director's 18-31s latency makes common, where
 * the clip ends before the next options exist.
 *
 * What the lead is *not* is a deadline. When the clip ends with nothing chosen,
 * the last frame holds and the story waits (`AUTO_ADVANCE_S = 0`). Deciding for
 * the player after 4s was the original behaviour and it was wrong: it read as the
 * game taking the choice away, and it bought nothing, because both branches are
 * already generated by then -- the GPUs are idle either way. Auto-advance is
 * still there for an unattended demo, just off.
 */

interface Props {
  sid: string;
  session: SessionView;
  connected: boolean;
  onExit: () => void;
}

type Mode = "idle" | "watching" | "deciding" | "waiting" | "blocked";

export default function Player({ sid, session, connected, onExit }: Props) {
  const stage = useRef<StageHandle>(null);
  const [shownId, setShownId] = useState<string | null>(null);
  const [mode, setMode] = useState<Mode>("idle");
  /**
   * The auto-advance countdown, 0 -> just ended, 1 -> expired. `null` whenever
   * nothing is counting, which with `AUTO_ADVANCE_S = 0` is always -- and the
   * overlay renders no ring at all in that case rather than a frozen one.
   */
  const [countdown, setCountdown] = useState<number | null>(null);
  const [clipEnded, setClipEnded] = useState(false);
  const [pending, setPending] = useState<number | null>(null);
  const [busy, setBusy] = useState(false);
  const [waitNote, setWaitNote] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [treeOpen, setTreeOpen] = useState(false);
  const [muted, setMuted] = useState(false);

  const committing = useRef(false);
  const pendingRef = useRef<number | null>(null);
  pendingRef.current = pending;

  const cursor = session.cursor ? session.beats[session.cursor] ?? null : null;
  // What the player is actually looking at, which is not always the server's
  // cursor: a free-text action moves the cursor immediately (so the Director
  // starts working) while the previous clip is still on screen.
  const shown = shownId ? session.beats[shownId] ?? null : null;

  // -- show the cursor's clip as soon as it exists ------------------------- //
  useEffect(() => {
    if (!cursor?.video_url) return;
    if (stage.current?.visible() === cursor.id) return;
    void stage.current?.show(cursor.id, cursor.video_url);
    setShownId(cursor.id);
    setMode("watching");
    setCountdown(null);
    setClipEnded(false);
    setPending(null);
    setWaitNote("");
    committing.current = false;
    setBusy(false);
  }, [cursor?.id, cursor?.video_url]);

  // -- keep both branches buffered ---------------------------------------- //
  useEffect(() => {
    if (!shown) return;
    for (const id of Object.values(shown.children)) {
      const child = session.beats[id];
      if (child?.video_url) stage.current?.buffer(child.id, child.video_url);
    }
  }, [shown, session.beats]);

  useEffect(() => {
    stage.current?.setMuted(muted);
  }, [muted]);

  // -- committing a choice ------------------------------------------------- //
  const commit = useCallback(
    async (body: { option_index?: number; custom_action?: string }) => {
      if (committing.current) return;
      committing.current = true;
      setBusy(true);
      try {
        await choose(sid, body);
      } catch (e) {
        committing.current = false;
        setBusy(false);
        setError(e instanceof Error ? e.message : String(e));
      }
    },
    [sid]
  );

  const onChoose = useCallback(
    (index: number) => {
      setPending(index);
      // Only commit now if the clip has already finished. Mid-clip, the choice is
      // remembered and committed at `ended` -- posting early would move the
      // server's cursor and cut the clip the player is still watching.
      if (clipEnded || mode === "waiting") void commit({ option_index: index });
    },
    [commit, clipEnded, mode]
  );

  const onCustom = useCallback(
    (action: string) => {
      // Committed immediately, unlike an option: this path has nothing
      // pre-generated behind it, so every second of the clip still playing is a
      // second of the Director's 18-31s taken off the visible wait.
      setPending(null);
      setWaitNote(action);
      void commit({ custom_action: action });
    },
    [commit]
  );

  const onEnded = useCallback(
    (beatId: string) => {
      const beat = session.beats[beatId];
      setClipEnded(true);
      if (!beat) return;
      if (beat.is_ending) {
        setMode("idle");
        return;
      }
      if (beat.options.length === 0) {
        // The Director has not answered yet. Hold on the last frame, which is
        // pixel-identical to the frame the decoder just left on screen.
        setMode("waiting");
        return;
      }
      setMode("deciding");
      if (pendingRef.current !== null) {
        // Already chosen mid-clip. This is the moment that choice was waiting
        // for, and committing it here is what makes the swap land exactly on the
        // clip boundary.
        void commit({ option_index: pendingRef.current });
      } else if (AUTO_ADVANCE_S > 0) {
        setCountdown(0);
      }
      // Otherwise: hold on the last frame and wait for the player. See the
      // header note on why that is the default.
    },
    [commit, session.beats]
  );

  // Options that arrive *after* the clip ended -- the Director was still working
  // when the picture ran out. Hand the decision to the player rather than making
  // it: they have been staring at a frozen frame waiting for exactly this, so
  // auto-committing here would be the worst possible moment to choose for them.
  // A choice they already clicked while waiting was committed on the spot by
  // `onChoose`, so there is nothing pending to flush.
  useEffect(() => {
    if (mode !== "waiting" || committing.current || !shown) return;
    if (shown.options.length === 0) return;
    if (waitNote) return; // a free-text action is already in flight
    setMode("deciding");
    if (AUTO_ADVANCE_S > 0) setCountdown(0);
  }, [mode, shown, waitNote]);

  const onTimeUpdate = useCallback(
    (beatId: string, time: number, duration: number) => {
      if (duration <= 0) return;
      // Raise the overlay early so the player can read both cards while the clip
      // is still running. No progress is tracked here: the lead is a head start,
      // not a timer, so there is nothing to count down.
      if (duration - time <= DECISION_LEAD_S) {
        const beat = session.beats[beatId];
        if (beat && beat.options.length > 0 && !beat.is_ending) setMode("deciding");
      }
    },
    [session.beats]
  );

  // The auto-advance countdown, when it is enabled at all. Driven by rAF rather
  // than a single timeout so the ring moves smoothly, and it commits from inside
  // the same loop so the visual and the action cannot disagree.
  useEffect(() => {
    if (countdown === null || AUTO_ADVANCE_S <= 0) return;
    const started = performance.now();
    let raf = 0;
    const tick = () => {
      const p = (performance.now() - started) / (AUTO_ADVANCE_S * 1000);
      if (p >= 1) {
        setCountdown(1);
        const beat = shownId ? session.beats[shownId] : null;
        if (beat && beat.options.length > 0) {
          void commit({ option_index: pendingRef.current ?? beat.predicted_choice });
        }
        return;
      }
      setCountdown(p);
      raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
    // Deliberately not depending on `session.beats`: re-running this on every
    // event would restart the countdown, and events arrive every few seconds.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [countdown === null, commit, shownId]);

  /**
   * Watch the clip that just ended once more.
   *
   * Only offered while the story is held at the end of a clip, which is also the
   * only window where it is free: the clip is already decoded in its slot, and
   * `AUTO_ADVANCE_S = 0` means nothing is counting down, so replaying costs the
   * player nothing and the GPUs are idle either way. Once a choice is committed
   * the cursor has moved and this beat is history -- the story tree is how you go
   * back to it, not this button.
   *
   * The overlay is dropped back to `watching` rather than kept up. The player
   * asked to *look* at the shot again, and `onTimeUpdate` re-raises the cards
   * `DECISION_LEAD_S` before the end anyway, so the choice comes back on its own
   * without ever having covered the picture they wanted to see.
   */
  const onReplay = useCallback(() => {
    if (!shown?.video_url) return;
    setClipEnded(false);
    setCountdown(null);
    setMode("watching");
    void stage.current?.show(shown.id, shown.video_url, true);
  }, [shown?.id, shown?.video_url]);

  const onSeek = useCallback(
    async (beatId: string) => {
      setTreeOpen(false);
      committing.current = false;
      try {
        await seek(sid, beatId);
      } catch (e) {
        setError(e instanceof Error ? e.message : String(e));
      }
    },
    [sid]
  );

  const childStatus = useCallback(
    (index: number) => {
      if (!shown) return null;
      const id = shown.children[String(index)];
      if (!id) return null;
      return session.beats[id]?.status ?? null;
    },
    [shown, session.beats]
  );

  const ending = shown?.is_ending ?? null;

  // The still under the overlay, rendered only once the clip has actually ended
  // -- while it is still playing the video itself is the picture.
  //
  // A paused <video> already shows its final frame, so this image is not there to
  // avoid a black screen; it is there for the slow Ken Burns push, which is what
  // makes an indefinite hold read as a held shot rather than as a stall. Which
  // matters much more now that the hold *is* indefinite by default.
  const freezeUrl =
    clipEnded && !ending ? shown?.last_frame_url ?? shown?.poster_url ?? null : null;

  /**
   * Fetch that still *during* playback, and do not reveal it until it has decoded.
   *
   * `last.png` is a lossless 480p frame -- 290-740KB, median 510KB -- because the
   * same file is the `fl2va` conditioning frame for the next beat, where
   * compression artefacts would compound down the chain. On localhost that loads
   * in single-digit milliseconds and mounting the <img> at `ended` was free. From
   * the orchestrator's new home it comes down an ssh tunnel from us-east-2:
   * measured 0.7-1.3s. For that whole window an unloaded <img> sat at z-index 3
   * over the video, so the clip ended and the picture blinked -- which is exactly
   * the flash that appeared the moment the service moved and did not exist before.
   *
   * Two fixes, because either alone leaves a hole: preload it (there are ~14s of
   * clip to do it in, so by `ended` it is in cache and `onLoad` fires at once),
   * and gate opacity on the load anyway, so a cold cache degrades to the video's
   * own last frame showing a moment longer instead of to a black rectangle.
   */
  const [freezeLoaded, setFreezeLoaded] = useState(false);
  useEffect(() => {
    setFreezeLoaded(false);
    const url = shown?.last_frame_url ?? shown?.poster_url ?? null;
    if (!url) return;
    const img = new Image();
    img.onload = () => setFreezeLoaded(true);
    img.src = url;
  }, [shown?.id, shown?.last_frame_url, shown?.poster_url]);

  const opening = !shown && session.phase !== "failed";
  const openingNote = useMemo(() => {
    if (session.phase === "creating") return "正在写世界圣经……";
    if (!session.bible) return "正在写世界圣经……";
    const root = session.root_id ? session.beats[session.root_id] : null;
    if (!root) return "正在构思第一个镜头……";
    switch (root.status) {
      case "compiling":
        return "正在编译第一个镜头的提示词……";
      case "queued":
        return "已排队，等待 GPU……";
      case "generating":
        return "正在生成第一段影像……";
      case "failed":
        return `第一段生成失败：${root.error ?? ""}`;
      default:
        return "正在准备第一段影像……";
    }
  }, [session.phase, session.bible, session.root_id, session.beats]);

  return (
    <div className="player">
      <VideoStage
        ref={stage}
        onTimeUpdate={onTimeUpdate}
        onEnded={onEnded}
        onBlocked={() => setMode("blocked")}
      />

      {freezeUrl ? (
        <img
          className="freeze"
          src={freezeUrl}
          style={{ opacity: freezeLoaded ? 1 : 0 }}
          onLoad={() => setFreezeLoaded(true)}
          alt=""
          aria-hidden
        />
      ) : null}

      {opening ? (
        <div className="curtain">
          {session.opening_keyframe_url ? (
            <img className="curtain-kf" src={session.opening_keyframe_url} alt="" />
          ) : null}
          <div className="curtain-body">
            {session.bible?.logline ? (
              <p className="logline">{session.bible.logline}</p>
            ) : null}
            <p className="curtain-note">
              <span className="spinner" /> {openingNote}
            </p>
          </div>
        </div>
      ) : null}

      {clipEnded && !ending && shown?.video_url && mode !== "blocked" ? (
        <button className="replay" onClick={onReplay} title="再看一遍这一段">
          <span aria-hidden>↺</span> 再看一遍
        </button>
      ) : null}

      {mode === "blocked" ? (
        <button className="blocked" onClick={() => void stage.current?.resume()}>
          点击继续播放
          <span>浏览器阻止了带声音的自动播放</span>
        </button>
      ) : null}

      {mode === "waiting" && shown && !ending ? (
        <div className="responding">
          <p>世界在回应你……</p>
          {waitNote ? <p className="responding-echo">「{waitNote}」</p> : null}
          <p className="responding-detail">
            {shown.options.length === 0
              ? "Director 正在写下一个岔路口"
              : "正在生成你选择的那一段"}
          </p>
        </div>
      ) : null}

      {ending ? (
        <div className="ending">
          <h2>{ending.title}</h2>
          <p>{ending.epilogue}</p>
          <button onClick={() => void onSeek(session.root_id ?? "")}>回到开头，换一条路</button>
        </div>
      ) : null}

      {mode === "deciding" && shown && shown.options.length > 0 ? (
        <DecisionOverlay
          beat={shown}
          countdown={countdown}
          held={clipEnded}
          childStatus={childStatus}
          chosen={pending}
          busy={busy}
          onChoose={onChoose}
          onCustom={onCustom}
        />
      ) : null}

      <Hud
        session={session}
        shown={shown}
        connected={connected}
        muted={muted}
        onToggleMute={() => setMuted((m) => !m)}
        onToggleTree={() => setTreeOpen((t) => !t)}
        treeOpen={treeOpen}
        onExit={onExit}
      />

      {treeOpen ? (
        <StoryTree session={session} onSeek={onSeek} onClose={() => setTreeOpen(false)} />
      ) : null}

      {error ? (
        <div className="toast" onClick={() => setError(null)}>
          {error}
        </div>
      ) : null}
    </div>
  );
}

export type { Beat };
